application:
  name: spectrum-qf-aws-application
file:
  root-dir:
  dest-dir:
s3:
  url:
  bucket:
  accessKey:
  secretKey:
  region: ap-southeast-1
smb:
  protocol:
    version: 2
  enabled: false
  from-dir:
  dest-dir:
  domain:
  username:
  password:
  service-name:
options:
  delete-files: false
  validation-phone-number: false
db:
  url:
  table-name: tmp_s3_files
  username:
  password:
