spring:
  application:
    name: spectrum-qf-aws-application
file:
  root-dir: /home/user/project/local
  dest-dir: /home/user/project/processed/
s3:
  url: http://192.168.110.110:9000
  bucket: kiwi
  accessKey: XY9grHx9CfFL32YU8vX0
  secretKey: YZ579SrTZfvGbGyGOFJgFgNWSaelB3RkkoISGCOT
  region: ap-southeast-1
