application:
  name: spectrum-qf-aws-application
file:
  root-dir: C:/Users/ashay/Desktop/s3/local
  dest-dir: C:/Users/ashay/Desktop/s3/processed/
s3:
  url: http://192.168.110.110:9000
  bucket: kiwi
  accessKey: XY9grHx9CfFL32YU8vX0
  secretKey: YZ579SrTZfvGbGyGOFJgFgNWSaelB3RkkoISGCOT
  region: ap-southeast-1
smb:
  protocol:
    version: 2
  enabled: true
  from-dir: smb://jenkins:jenkins@bkp01.it-spectrum.ru/smb-tst/smb/
  dest-dir: smb://jenkins:jenkins@bkp01.it-spectrum.ru/smb-tst/processed/
  domain: it-spectrum
  username: jenkins
  password: jenkins
  service-name: smb-tst
options:
  delete-files: false
db:
  url: jdbc:oracle:thin:@192.168.1.16:1521:sskvdev
  table-name: tmp_s3_files
  username: ssv
  password: ssv
